spring:
    application:
        name: spring-watermark
    # redis配置，以下有默认配置的也可以使用默认配置
    redis:
        host: 120.79.188.188
        port: 16379
        database: 5
        password: MbiXx1Zp22
        timeout: 20000
        #cluster:
            #nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
            #maxRedirects: 6
        lettuce:
          pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
